import { StyleSheet } from 'react-native'

import { Typography } from '@/config/constants/theme'

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F7FBF5' },
  content: { paddingHorizontal: 16, paddingBottom: 30 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 22,
    paddingBottom: 18,
    backgroundColor: '#F7FBF5',
    position: 'relative',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: Typography.screenHeaderFontSize,
    fontWeight: '900',
    color: '#081A13',
  },
  headerActions: { position: 'absolute', right: 22, flexDirection: 'row', gap: 12 },
  headerIconButton: { padding: 4 },
  controlCard: { backgroundColor: '#CFECC2', borderRadius: 16, padding: 16, marginBottom: 16 },
  fieldLabel: { fontSize: 13, fontWeight: '700', color: '#245442', marginBottom: 10 },
  chipRow: { flexDirection: 'row', gap: 8 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: '#E9F8E2' },
  chipActive: { backgroundColor: '#12392C' },
  chipText: { fontSize: 12, fontWeight: '700', color: '#12392C' },
  chipTextActive: { color: '#FFFFFF' },
  searchField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E9F8E2',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchInput: { flex: 1, fontSize: 13, color: '#0B2C20' },
  emptyText: {
    color: '#245442',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
    paddingHorizontal: 12,
    paddingVertical: 22,
    textAlign: 'center',
  },
  budgetCard: {
    backgroundColor: '#79C77C',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  budgetHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  budgetIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#79C77C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  budgetTitleArea: { flex: 1, marginLeft: 12 },
  budgetTitle: { fontSize: 16, fontWeight: '800', color: '#12392C' },
  budgetSub: { fontSize: 12, color: '#174838', marginTop: 2, fontWeight: '700' },
  budgetActions: { flexDirection: 'row', gap: 12 },
  progressContainer: { marginTop: 4 },
  progressBarBg: {
    height: 8,
    backgroundColor: '#DDF2D2',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBarFill: { height: '100%', borderRadius: 4 },
  progressTextRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  progressText: { fontSize: 12, color: '#12392C', fontWeight: '700' },
})
