import { StyleSheet } from 'react-native'

import { Typography } from '@/config/constants/theme'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FBF5',
  },
  statisticsContainer: {
    flex: 1,
  },
  periodFilterContainer: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
  },
  periodFilterButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 11,
  },
  periodFilterButtonActive: {
    backgroundColor: '#245442',
  },
  periodFilterText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#245442',
  },
  periodFilterTextActive: {
    color: '#FFFFFF',
  },
  periodNavigationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
  },
  periodNavButton: {
    padding: 8,
  },
  periodLabel: {
    fontSize: 17,
    fontWeight: '900',
    color: '#081A13',
  },
  typeToggleContainer: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
  },
  typeToggleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 11,
  },
  typeToggleButtonActive: {
    backgroundColor: '#245442',
  },
  typeToggleText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#245442',
  },
  typeToggleTextActive: {
    color: '#FFFFFF',
  },
  totalAmountContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#79C77C',
  },
  totalAmountValue: {
    fontSize: 30,
    fontWeight: '900',
    color: '#081A13',
  },
  chartContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    alignItems: 'center',
  },
  pieChartContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    width: '100%',
  },
  pieChartPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E9F8E2',
    position: 'relative',
  },
  pieChartCenter: {
    position: 'absolute',
    top: 30,
    left: 30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
  },
  pieChartLegend: {
    flex: 1,
    flexDirection: 'column',
    gap: 8,
  },
  pieChartLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 4,
  },
  pieChartLegendColor: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  pieChartLegendColorSelected: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#245442',
  },
  pieChartLegendText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#72777E',
  },
  pieChartLegendTextSelected: {
    color: '#245442',
    fontWeight: '900',
  },
  emptyChartContainer: {
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyChartText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#72777E',
  },
  categoryListContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
  },
  categoryListTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#081A13',
    marginBottom: 14,
  },
  categoryListScroll: {
    flex: 1,
  },
  categoryListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginBottom: 8,
  },
  categoryListItemSelected: {
    backgroundColor: '#E9F8E2',
    borderWidth: 1.5,
    borderColor: '#79C77C',
  },
  categoryListIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryListInfo: {
    flex: 1,
  },
  categoryListName: {
    fontSize: 16,
    fontWeight: '900',
    color: '#081A13',
  },
  categoryListPercentage: {
    fontSize: 13,
    fontWeight: '700',
    color: '#72777E',
    marginTop: 2,
  },
  categoryListAmount: {
    fontSize: 16,
    fontWeight: '900',
    color: '#081A13',
    marginRight: 8,
  },
  detailScreen: {
    flex: 1,
    backgroundColor: '#F7FBF5',
  },
  content: {
    paddingHorizontal: 10,
    paddingBottom: 30,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 22,
    paddingBottom: 18,
    backgroundColor: '#F7FBF5',
    position: 'relative',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: Typography.screenHeaderFontSize,
    fontWeight: '900',
    color: '#081A13',
  },
  headerActions: {
    position: 'absolute',
    right: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailHeader: {
    minHeight: 90,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingBottom: 12,
    gap: 8,
  },
  detailBackButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E9F8E2',
    borderWidth: 1,
    borderColor: 'rgba(18, 57, 44, 0.14)',
  },
  detailHeaderTitle: {
    flex: 1,
    color: '#081A13',
    fontSize: 19,
    fontWeight: '900',
  },
  detailHeaderActions: {
    minWidth: 72,
    height: 34,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E9F8E2',
    borderWidth: 1,
    borderColor: 'rgba(18, 57, 44, 0.14)',
  },
  detailHeaderActionButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailHeaderDivider: {
    width: 1,
    height: 16,
    backgroundColor: 'rgba(18, 57, 44, 0.28)',
  },
  detailScrollContent: {
    paddingHorizontal: 14,
  },
  transactionDetailPanel: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 26,
    overflow: 'hidden',
  },
  detailHero: {
    minHeight: 118,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#79C77C',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
  },
  detailHeroIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E9F8E2',
  },
  detailHeroText: {
    flex: 1,
    minWidth: 0,
  },
  detailHeroNote: {
    color: '#72777E',
    fontSize: 15,
    fontWeight: '500',
    textTransform: 'uppercase',
  },
  detailHeroAmount: {
    marginTop: 7,
    fontSize: 26,
    lineHeight: 31,
    fontWeight: '900',
  },
  detailHeroCurrency: {
    fontSize: 19,
  },
  transactionDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 22,
  },
  transactionDetailLabel: {
    flex: 0.72,
    color: '#75787D',
    fontSize: 17,
    fontWeight: '500',
  },
  transactionDetailValue: {
    flex: 1.5,
    color: '#2A2D31',
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'right',
  },
  transactionDetailWalletValue: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
  },
  transactionDetailWalletText: {
    flexShrink: 1,
    color: '#2A2D31',
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'right',
  },
  detailMissingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  detailMissingText: {
    color: '#2A2D31',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  pageTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
    borderRadius: 14,
    backgroundColor: '#E9F8E2',
    padding: 4,
  },
  pageTab: {
    flex: 1,
    minHeight: 42,
    borderRadius: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  pageTabActive: {
    backgroundColor: '#FFFFFF',
  },
  pageTabText: {
    color: '#5D6B66',
    fontSize: 15,
    fontWeight: '800',
  },
  pageTabTextActive: {
    color: '#245442',
    fontWeight: '900',
  },
  statisticsContent: {
    minHeight: 360,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statisticsText: {
    color: '#245442',
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyText: {
    color: '#245442',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
    paddingHorizontal: 12,
    paddingVertical: 22,
    textAlign: 'center',
  },
  controlCard: {
    backgroundColor: '#CFECC2',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  controlHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0B2C20',
    textAlign: 'center',
  },
  fieldLabel: {
    marginTop: 14,
    fontSize: 13,
    fontWeight: '700',
    color: '#245442',
  },
  fieldSpacing: {
    marginTop: 16,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: '#E9F8E2',
  },
  chipActive: {
    backgroundColor: '#12392C',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#12392C',
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  searchField: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E9F8E2',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0B2C20',
    paddingVertical: 0,
  },
  detailCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 14,
    marginBottom: 12,
    position: 'relative',
  },
  detailCardLight: {
    backgroundColor: '#79C77C',
  },
  detailCardDark: {
    backgroundColor: '#12392C',
  },
  detailCategoryIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBody: {
    flex: 1,
    minWidth: 0,
    paddingRight: 4,
  },
  detailNote: {
    color: '#103529',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 20,
  },
  detailDate: {
    marginTop: 5,
    color: '#174838',
    fontSize: 12,
    fontWeight: '800',
  },
  detailTextOnDark: {
    color: '#FFFFFF',
  },
  detailSecondaryTextOnDark: {
    color: '#E9F8E2',
  },
  detailCategoryBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.24)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 8,
    maxWidth: '100%',
  },
  detailCategoryText: {
    color: '#103529',
    fontSize: 12,
    fontWeight: '900',
  },
  detailAmount: {
    color: '#252A31',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 20,
    textAlign: 'right',
  },
  detailAmountCurrency: {
    fontSize: 13,
    color: '#FFFFFF',
  },
  detailSide: {
    width: 104,
    alignItems: 'flex-end',
  },
  detailWalletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 5,
    marginTop: 9,
    maxWidth: '100%',
    flexWrap: 'wrap',
  },
  detailWalletMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 3,
    maxWidth: '100%',
  },
  detailWalletText: {
    flexShrink: 1,
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'right',
    lineHeight: 13,
  },
  detailActions: {
    position: 'absolute',
    right: 10,
    bottom: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  editButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(18,57,44,0.22)',
  },
  aiCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ECF0EF',
    padding: 10,
    marginBottom: 12,
  },
  aiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 9,
  },
  aiTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  aiIconBox: {
    width: 22,
    height: 22,
    borderRadius: 5,
    backgroundColor: '#E8FBFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiTitle: {
    color: '#353C45',
    fontSize: 16,
    fontWeight: '900',
  },
  aiContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  aiChart: {
    width: 156,
    height: 96,
    borderRadius: 8,
    backgroundColor: '#F0F8FF',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    paddingHorizontal: 12,
    paddingBottom: 10,
    paddingTop: 8,
  },
  aiBarColumn: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
  },
  aiBar: {
    width: 34,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  aiMonthLabel: {
    color: '#8A929D',
    fontSize: 10,
    fontWeight: '800',
  },
  aiSummary: {
    flex: 1,
    minWidth: 0,
  },
  aiCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  aiCategoryText: {
    flex: 1,
    color: '#5A626D',
    fontSize: 12,
    fontWeight: '800',
  },
  aiDescription: {
    color: '#555C65',
    fontSize: 11,
    marginTop: 5,
  },
  aiAmount: {
    color: '#353C45',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 2,
  },
  categoryTabs: {
    marginHorizontal: -10,
    marginBottom: 10,
  },
  categoryTabsContent: {
    paddingHorizontal: 10,
    gap: 18,
  },
  categoryTab: {
    minHeight: 38,
    justifyContent: 'flex-start',
    position: 'relative',
    paddingTop: 4,
  },
  categoryTabText: {
    color: '#0B1D17',
    fontSize: 15,
    fontWeight: '500',
  },
  categoryTabTextActive: {
    color: '#245442',
    fontWeight: '900',
  },
  categoryTabIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    borderRadius: 999,
    backgroundColor: '#245442',
  },
  legendContainer: {
    marginTop: 10,
    width: '100%',
    paddingHorizontal: 20,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  dot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  legendText: {
    fontSize: 14,
    color: '#333',
  },
})
