import { StyleSheet } from 'react-native'

import { Typography } from '@/config/constants/theme'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FBF5',
  },
  content: {
    paddingHorizontal: 10,
    paddingBottom: 30,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 22,
    paddingBottom: 18,
    backgroundColor: '#F7FBF5',
    position: 'relative',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: Typography.screenHeaderFontSize,
    fontWeight: '900',
    color: '#081A13',
  },
  headerActions: {
    position: 'absolute',
    right: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlCard: {
    backgroundColor: '#CFECC2',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  controlHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0B2C20',
    textAlign: 'center',
  },
  fieldLabel: {
    marginTop: 14,
    fontSize: 13,
    fontWeight: '700',
    color: '#245442',
  },
  fieldSpacing: {
    marginTop: 16,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: '#E9F8E2',
  },
  chipActive: {
    backgroundColor: '#12392C',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#12392C',
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  searchField: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E9F8E2',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0B2C20',
    paddingVertical: 0,
  },
  detailCard: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    marginBottom: 16,
  },
  detailCardLight: {
    backgroundColor: '#79C77C',
  },
  detailCardDark: {
    backgroundColor: '#12392C',
  },
  detailActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  editButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  detailHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailCategoryRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  detailCategoryIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailCategoryTitle: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  detailAmount: {
    marginTop: 16,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 32,
  },
  detailAmountCurrency: {
    fontSize: 17,
    color: 'rgba(255, 232, 226, 0.72)',
  },
  detailIconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: '54%',
  },
  detailIconWrapDark: {
    gap: 6,
  },
  detailRoundIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#12392C',
  },
  detailFooterTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  transferCardBody: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  transferAmount: {
    marginTop: 16,
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
  },
  transferCurrency: {
    fontSize: 19,
    color: 'rgba(185, 255, 208, 0.72)',
  },
  transferIconsCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexWrap: 'wrap',
    marginTop: 10,
  },
  transferPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F6F2ED',
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  transferPillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0B1D17',
  },
  detailInfo: {
    marginTop: 12,
    gap: 7,
  },
  detailLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  detailLineText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 12,
  },
  tipBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#E9F8E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  tipBadgeText: {
    color: '#E9F8E2',
    fontSize: 10,
    fontWeight: '900',
  },
  tipText: {
    flex: 1,
    color: '#E9F8E2',
    fontSize: 10,
    fontStyle: 'italic',
    lineHeight: 14,
  },
})
