import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F1EF',
  },
  content: {
    paddingHorizontal: 10,
    paddingBottom: 30,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 12,
    marginBottom: 22,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 30,
    fontWeight: '900',
    color: '#081A13',
  },
  headerActions: {
    position: 'absolute',
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlCard: {
    backgroundColor: '#E7E0D9',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  controlHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0B2C20',
    textAlign: 'center',
  },
  fieldLabel: {
    marginTop: 14,
    fontSize: 13,
    fontWeight: '700',
    color: '#23473A',
  },
  fieldSpacing: {
    marginTop: 16,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: '#F7F3EF',
  },
  chipActive: {
    backgroundColor: '#0A3A2A',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#164634',
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  searchField: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F7F3EF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  statusCard: {
    backgroundColor: '#F7F3EF',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
    alignItems: 'center',
    gap: 8,
  },
  statusText: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '700',
    color: '#0B2C20',
  },
  retryButton: {
    backgroundColor: '#0A3A2A',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0B2C20',
    paddingVertical: 0,
  },
  detailCard: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    marginBottom: 16,
  },
  detailCardLight: {
    backgroundColor: '#179041',
  },
  detailCardDark: {
    backgroundColor: '#08251A',
  },
  detailActions: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 4,
  },
  editButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  detailAmount: {
    flex: 1,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 32,
  },
  detailIconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: '54%',
  },
  detailIconWrapDark: {
    gap: 6,
  },
  detailRoundIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0A4D2E',
  },
  detailFooterTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  transferCardBody: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  transferAmount: {
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
    textAlign: 'center',
  },
  transferIconsCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  transferPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F6F2ED',
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  transferPillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0B1D17',
  },
  detailInfo: {
    marginTop: 12,
    gap: 7,
  },
  detailLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  detailLineText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 12,
  },
  tipBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#E7FFF0',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  tipBadgeText: {
    color: '#E7FFF0',
    fontSize: 10,
    fontWeight: '900',
  },
  tipText: {
    flex: 1,
    color: '#ECFFF5',
    fontSize: 10,
    fontStyle: 'italic',
    lineHeight: 14,
  },
})
