import { Platform, StyleSheet } from 'react-native'

export const colors = {
  background: '#f8f5ef',
  border: '#5e7468',
  dark: '#111111',
  green: '#003d2b',
  muted: '#7f807c',
  placeholder: '#8a8a86',
  surface: '#ffffff',
  success: '#064e3b',
  error: '#a33024',
}

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 23,
    paddingTop: 52,
    paddingBottom: 32,
  },
  title: {
    color: colors.dark,
    fontSize: 33,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 42,
    marginBottom: 45,
    textAlign: 'center',
  },
  emailField: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1.2,
    flexDirection: 'row',
    gap: 12,
    height: 56,
    paddingHorizontal: 10,
  },
  emailInput: {
    color: colors.dark,
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    height: '100%',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 8,
    height: 56,
    justifyContent: 'center',
    marginTop: 34,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0,
  },
  dividerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 18,
    marginBottom: 69,
    marginTop: 64,
  },
  dividerLine: {
    backgroundColor: colors.border,
    flex: 1,
    height: 1.2,
  },
  dividerText: {
    color: colors.dark,
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: 0,
  },
  socialButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1.2,
    flexDirection: 'row',
    gap: 16,
    height: 56,
    justifyContent: 'center',
    marginBottom: 28,
    paddingHorizontal: 16,
  },
  socialButtonText: {
    color: colors.green,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0,
  },
  disabledButton: {
    opacity: 0.7,
  },
  pressed: {
    opacity: 0.8,
  },
  message: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    marginTop: 4,
    textAlign: 'center',
  },
  successText: {
    color: colors.success,
  },
  errorText: {
    color: colors.error,
  },
  homeContent: {
    flexGrow: 1,
    paddingHorizontal: 23,
    paddingTop: 32,
    paddingBottom: 34,
  },
  homeHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  avatar: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 36,
    borderWidth: 1,
    height: 72,
    width: 72,
  },
  avatarFallback: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 36,
    borderWidth: 1,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  homeTitleGroup: {
    flex: 1,
  },
  welcomeLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  homeTitle: {
    color: colors.dark,
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 32,
  },
  homeSubtitle: {
    color: colors.green,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    marginTop: 4,
  },
  statusPanel: {
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    borderColor: '#9bd0b8',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  statusText: {
    color: colors.success,
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  section: {
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
    padding: 14,
  },
  sectionTitle: {
    color: colors.dark,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginBottom: 12,
  },
  detailRow: {
    borderTopColor: '#d7d1c7',
    borderTopWidth: 1,
    paddingVertical: 10,
  },
  detailLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  detailValue: {
    color: colors.dark,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  jsonBlock: {
    color: colors.dark,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
    fontSize: 12,
    lineHeight: 18,
  },
  tokenSummary: {
    color: colors.green,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  signOutButton: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    height: 54,
    justifyContent: 'center',
    marginTop: 4,
  },
  signOutButtonText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
  },
})
