import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F4F1EF' },
  content: { paddingHorizontal: 16, paddingBottom: 30 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 22,
  },
  headerTitle: { flex: 1, textAlign: 'center', fontSize: 24, fontWeight: '900', color: '#081A13' },
  headerActions: { position: 'absolute', right: 0, flexDirection: 'row', gap: 12 },
  headerIconButton: { padding: 4 },
  controlCard: { backgroundColor: '#E7E0D9', borderRadius: 16, padding: 16, marginBottom: 16 },
  fieldLabel: { fontSize: 13, fontWeight: '700', color: '#23473A', marginBottom: 10 },
  chipRow: { flexDirection: 'row', gap: 8 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: '#F7F3EF' },
  chipActive: { backgroundColor: '#0A3A2A' },
  chipText: { fontSize: 12, fontWeight: '700', color: '#164634' },
  chipTextActive: { color: '#FFFFFF' },
  searchField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F7F3EF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchInput: { flex: 1, fontSize: 13, color: '#0B2C20' },
  limitCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  limitHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  limitIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#198B3F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  limitTitleArea: { flex: 1, marginLeft: 12 },
  limitTitle: { fontSize: 16, fontWeight: '800', color: '#0B1D17' },
  limitSub: { fontSize: 12, color: '#666', marginTop: 2 },
  limitActions: { flexDirection: 'row', gap: 12 },
  progressContainer: { marginTop: 4 },
  progressBarBg: { height: 8, backgroundColor: '#E0E0E0', borderRadius: 4, overflow: 'hidden' },
  progressBarFill: { height: '100%', borderRadius: 4 },
  progressTextRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  progressText: { fontSize: 12, color: '#444' },
})
